### PR TITLE
fix: replace hardcoded project with the project variable

### LINKED ISSUE #98: Cannot create subsets for projects other than "gecko"
We hardcoded "gecko":

https://github.com/molgenis/molgenis-r-armadillo/blame/d1e4a4b96295bacd35efb711c3ff19892930caab/R/subset.R#L85

https://github.com/molgenis/molgenis-r-armadillo/blob/d1e4a4b96295bacd35efb711c3ff19892930caab/R/subset.R#L85

We also have to check if this actually was a breaking change and in that case make it not breaking since we did not want a major release.

### PR DESCRIPTION
**Pull request by marikaris**
closes #98

To test:
Run armadillo on localhost. Make sure the demo project lifecycle is in there with its demo data as in the armadillo repo.
Download this file: 
[vars.csv](https://github.com/molgenis/molgenis-r-armadillo/files/13345884/vars.csv)

It contains the subset definition as in the demo code for the "lifecycle" test project. 
Create the subset definition:
``` R
subset_definition <- armadillo.subset_definition(vars ="path/to/vars.csv")
armadillo.subset(source_project = "lifecycle", new_project = "study1", subset_def = subset_definition, dry_run = FALSE)
```
Go to localhost and see study 1 is there with in the "core" folder the "nonrep" and "yearlyrep" and in "outcome" only "yearlyrep"

### CODE REVIEW

File: R/subset.R [hunk 1]
```diff
@@ -82,7 +82,7 @@ armadillo.subset <- function(source_project = NULL,
   type <- folder <- . <- NULL
 
   suppressMessages(
-    source_tables <- within(armadillo.list_tables("gecko") %>%
+    source_tables <- within(armadillo.list_tables(source_project) %>%
```
Comment (clemens-tolboom) [inline R/subset.R:85]: Should you test (tests/testthat/test-subset.R) with another name then 'gecko'?

The docs use gecko so it probably is OK

**Review by clemens-tolboom — APPROVED** [review]
LGTM if no problem using gecko
